# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Veggie Kebabs of Berlin
email: Veggiekebabsofberlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A limited but wonderful guide to veggie kebab houses in Berlin. Very important information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kebabsofberlin.github.io" # the base hostname & protocol for your site
twitter_username: veggiekebabsofberlin
github_username:  Veggiekebabsofberlin

# Build settings
markdown: kramdown
